GET http://localhost:3000/Inbox/643f119ba038bb259dbde84d

###

POST http://localhost:3000/Inbox
Content-Type: application/json

{
    "conversationID" : 1122334457,
    "itemName": "Nintendo 64 Console - Japanese Import",
    "itemSrc": "https://m.media-amazon.com/images/I/51Lh2WVlJIL._AC_.jpg"
}

###

GET http://localhost:3000/userConversations/64481c51b2c38c08980e063c

